import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AntigravityLogo } from '@/components/ui/AntigravityLogo';
import { Button } from '@/components/ui/Button';
import { WaitlistModal } from '@/components/landing/WaitlistModal';
import { ArrowRight, Check, ChevronRight, CircleCheck, Radio, ShieldCheck, Sparkles, Ticket, Users } from 'lucide-react';

const moments = [
  ['01', 'Arrive without friction', 'A ticket lives on the guest’s phone. Gates scan quickly, entry stays orderly, and your team can see the pace in real time.', Ticket],
  ['02', 'Keep the crowd in flow', 'See where people are gathering before it becomes a problem. Open another route, pause a gate, or send the right team early.', Users],
  ['03', 'End on a high note', 'Give every attendee a calmer way home with live updates, an incident trail, and a team that is always coordinated.', ShieldCheck],
] as const;

export const CleanLandingPage: React.FC = () => {
  const navigate = useNavigate();
  const [isWaitlistOpen, setIsWaitlistOpen] = useState(false);

  return (
    <main className="min-h-screen overflow-x-hidden bg-[#f8f8f6] text-[#171716] selection:bg-[#d8ff54] selection:text-[#171716]">
      <header className="sticky top-0 z-40 border-b border-black/5 bg-[#f8f8f6]/90 px-5 backdrop-blur-xl sm:px-8 lg:px-12">
        <div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between">
          <Link to="/" aria-label="Antigravity home" className="shrink-0"><AntigravityLogo size="md" /></Link>
          <nav className="hidden items-center gap-8 text-sm font-medium text-black/55 md:flex" aria-label="Primary navigation"><a className="transition hover:text-black" href="#experience">The experience</a><a className="transition hover:text-black" href="#operations">For organisers</a><a className="transition hover:text-black" href="#safety">Safety, quietly built in</a></nav>
          <div className="flex items-center gap-2 sm:gap-3"><button onClick={() => setIsWaitlistOpen(true)} className="hidden text-sm font-semibold text-black/65 transition hover:text-black sm:block">Talk to us</button><Button size="sm" variant="primary" onClick={() => navigate('/dashboard')} className="bg-[#171716] px-4 text-xs font-bold text-white shadow-none hover:bg-black sm:px-5">Open command centre</Button></div>
        </div>
      </header>

      <section className="px-5 pb-14 pt-14 sm:px-8 sm:pb-20 sm:pt-20 lg:px-12 lg:pt-24"><div className="mx-auto max-w-7xl"><div className="grid items-end gap-10 lg:grid-cols-[1.08fr_.92fr] lg:gap-16"><div className="max-w-3xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-black/10 bg-white px-3 py-1.5 text-xs font-semibold text-black/65"><span className="h-2 w-2 rounded-full bg-[#a3df00]" />Built for live events in Kenya</div><h1 className="max-w-3xl text-[clamp(3.4rem,8vw,7.25rem)] font-semibold leading-[.92] tracking-[-0.075em] text-[#171716]">Better nights out start with better flow.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-black/60 sm:text-xl">Antigravity makes every part of a live event feel considered — from a ticket that just works to a venue team that is always one step ahead.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row sm:items-center"><Button size="lg" variant="primary" onClick={() => navigate('/dashboard')} rightIcon={<ArrowRight className="h-4 w-4" />} className="h-13 bg-[#171716] px-6 text-sm font-bold text-white shadow-none hover:bg-black">See the live view</Button><button onClick={() => setIsWaitlistOpen(true)} className="flex h-12 items-center justify-center gap-1 text-sm font-bold text-[#171716] transition hover:gap-2">Plan your next event <ChevronRight className="h-4 w-4" /></button></div></div>
        <div className="relative overflow-hidden rounded-[28px] bg-[#171716] p-5 text-white shadow-[0_24px_70px_rgba(22,22,20,.16)] sm:p-7"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-[#d8ff54] opacity-95 blur-3xl" /><div className="relative flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-white/45">Tonight at KICC</p><p className="mt-1 text-lg font-semibold tracking-tight">Nairobi Sounds · Live</p></div><div className="flex items-center gap-1.5 rounded-full bg-[#d8ff54] px-3 py-1.5 text-xs font-bold text-[#171716]"><Radio className="h-3.5 w-3.5" />Live</div></div><div className="relative mt-8 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/50">Guests inside</p><p className="mt-2 text-3xl font-semibold tracking-[-.05em]">7,842</p><p className="mt-2 text-xs font-medium text-[#d8ff54]">+412 in the last 10 min</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/50">Venue pulse</p><p className="mt-2 text-3xl font-semibold tracking-[-.05em]">Calm</p><p className="mt-2 flex items-center gap-1 text-xs font-medium text-[#d8ff54]"><CircleCheck className="h-3.5 w-3.5" />All zones flowing</p></div></div><div className="relative mt-3 rounded-2xl bg-white p-4 text-[#171716]"><div className="flex items-center justify-between"><p className="text-sm font-bold">The next best move</p><Sparkles className="h-4 w-4 text-[#709900]" /></div><p className="mt-2 text-sm leading-relaxed text-black/60">Open East Gate for the next 15 minutes. It will keep arrivals evenly distributed.</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-black/8"><div className="h-full w-[68%] rounded-full bg-[#a3df00]" /></div></div></div></div>
        <div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 border-t border-black/10 pt-7 text-sm font-medium text-black/55">{['M-Pesa-native ticketing', 'Live gate and crowd signals', 'One shared safety view'].map((point) => <span key={point} className="flex items-center gap-2"><Check className="h-4 w-4 text-[#709900]" />{point}</span>)}</div></div></section>

      <section id="experience" className="border-y border-black/8 bg-white px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.15em] text-[#709900]">A guest-first operating system</p><h2 className="mt-4 text-4xl font-semibold leading-[.98] tracking-[-.06em] sm:text-5xl">The safest event is one that never feels managed.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-3">{moments.map(([number, title, body, Icon]) => <article key={number} className="rounded-3xl border border-black/8 bg-[#f8f8f6] p-6 sm:p-7"><div className="flex items-start justify-between"><span className="text-sm font-bold text-black/35">{number}</span><Icon className="h-5 w-5 text-[#709900]" /></div><h3 className="mt-12 text-2xl font-semibold tracking-[-.04em]">{title}</h3><p className="mt-3 text-base leading-relaxed text-black/60">{body}</p></article>)}</div></div></section>

      <section id="operations" className="bg-[#d8ff54] px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.82fr_1.18fr] lg:gap-20"><div><p className="text-sm font-bold uppercase tracking-[.15em] text-black/55">Built for the people in charge</p><h2 className="mt-4 text-4xl font-semibold leading-[.98] tracking-[-.06em] sm:text-5xl">Less dashboard. More decision.</h2><p className="mt-6 max-w-md text-lg leading-relaxed text-black/65">Give your operations team one calm, shared picture of the event — so they can act on the signal that matters, not hunt through data.</p><Button size="lg" variant="primary" onClick={() => navigate('/dashboard')} className="mt-8 bg-[#171716] px-6 text-sm font-bold text-white shadow-none hover:bg-black">Explore the command centre</Button></div><div className="rounded-[28px] bg-[#171716] p-6 text-white sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-white/45">Event health</p><p className="mt-1 text-xl font-semibold">Everything is moving</p></div><div className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold">8:42 PM</div></div><div className="mt-8 space-y-3">{[['Entry', '4,208 guests', 'Smooth'], ['Main floor', '68% capacity', 'Comfortable'], ['Perimeter', '6 team members', 'Covered']].map(([label, value, status]) => <div key={label} className="flex items-center justify-between rounded-2xl bg-white/10 px-4 py-4"><div><p className="text-sm font-bold">{label}</p><p className="mt-1 text-xs text-white/55">{value}</p></div><span className="rounded-full bg-[#d8ff54] px-2.5 py-1 text-xs font-bold text-[#171716]">{status}</span></div>)}</div></div></div></section>

      <section id="safety" className="px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto max-w-7xl rounded-[32px] bg-[#20201e] px-6 py-12 text-white sm:px-12 sm:py-16"><div className="grid gap-10 lg:grid-cols-[1fr_.85fr] lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[.15em] text-[#d8ff54]">Safety, quietly built in</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold leading-[.98] tracking-[-.06em] sm:text-5xl">Make the right thing the easy thing.</h2></div><div><p className="text-base leading-relaxed text-white/60">Antigravity connects ticketing, live crowd flow, team communication and post-event reporting into one considered system. No extra drama. Just a better event for everyone.</p><button onClick={() => setIsWaitlistOpen(true)} className="mt-6 flex items-center gap-2 text-sm font-bold text-[#d8ff54]">Talk to the Nairobi team <ArrowRight className="h-4 w-4" /></button></div></div></div></section>
      <footer className="border-t border-black/8 px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm text-black/50 sm:flex-row sm:items-center sm:justify-between"><AntigravityLogo size="sm" /><p>Designed for safer, more memorable live events.</p><p>© 2026 Antigravity</p></div></footer>
      <WaitlistModal isOpen={isWaitlistOpen} onClose={() => setIsWaitlistOpen(false)} />
    </main>
  );
};
