import React, { useMemo } from 'react';
import { useAppStore } from '@/lib/store';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Activity, CheckCircle2, ClipboardList, MapPin, Radio, Store, Users } from 'lucide-react';

export const EventDayBoard: React.FC<{ eventId: string; onOpenLive: () => void }> = ({ eventId, onOpenLive }) => {
  const { eventTasks, eventSuppliers, updateEventTask, updateEventSupplier } = useAppStore();
  const tasks = useMemo(() => eventTasks.filter((task) => task.event_id === eventId && task.status !== 'complete'), [eventTasks, eventId]);
  const suppliers = useMemo(() => eventSuppliers.filter((supplier) => supplier.event_id === eventId), [eventSuppliers, eventId]);
  const onSite = suppliers.filter((supplier) => supplier.status === 'on_site').length;

  return <div className="space-y-5">
    <Card className="overflow-hidden border-ag-green/30 bg-gradient-to-r from-ag-green-dim/20 to-ag-surface p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-ag-green"><span className="h-2 w-2 rounded-full bg-ag-green animate-pulse" /><p className="text-xs font-bold uppercase tracking-wider">Event-day coordination</p></div><h2 className="mt-2 text-xl font-bold text-white">Run the event without chasing people.</h2><p className="mt-1 text-sm text-ag-text-secondary">Teams acknowledge their work here; the command centre handles live safety and crowd decisions.</p></div><Button size="md" variant="primary" onClick={onOpenLive} rightIcon={<Radio className="h-4 w-4" />} className="bg-ag-green font-bold text-black hover:bg-ag-green/90">Open command centre</Button></div></Card>
    <div className="grid gap-4 md:grid-cols-3"><DayMetric icon={<ClipboardList className="h-4 w-4" />} label="Tasks to run" value={String(tasks.length)} detail="each needs a current owner" color="blue" /><DayMetric icon={<Store className="h-4 w-4" />} label="Suppliers on site" value={`${onSite} / ${suppliers.length}`} detail="arrival status is shared" color="green" /><DayMetric icon={<Users className="h-4 w-4" />} label="Team views" value="4" detail="organiser, finance, supplier, operations" color="yellow" /></div>
    <div className="grid gap-5 lg:grid-cols-2"><Card className="p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-wider text-ag-text-muted">My team’s live work</p><h3 className="mt-1 text-lg font-bold text-white">Assign, acknowledge, complete</h3><div className="mt-5 space-y-2">{tasks.map((task) => <div key={task.id} className="rounded-xl border border-ag-border bg-ag-black/30 p-3"><div className="flex items-start gap-3"><div className="rounded-lg bg-ag-blue-dim p-2 text-ag-blue"><Activity className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-bold text-white">{task.title}</p><p className="mt-0.5 text-xs text-ag-text-secondary">{task.owner_name} · {task.workstream}</p></div></div><div className="mt-3 flex gap-2"><button onClick={() => updateEventTask(task.id, { status: 'in_progress' })} className="rounded-md bg-ag-surface px-2.5 py-1.5 text-[11px] font-bold text-ag-blue">Acknowledged</button><button onClick={() => updateEventTask(task.id, { status: 'complete' })} className="rounded-md bg-ag-green-dim px-2.5 py-1.5 text-[11px] font-bold text-ag-green">Mark complete</button></div></div>)}{tasks.length === 0 && <div className="rounded-xl border border-dashed border-ag-border p-5 text-center"><CheckCircle2 className="mx-auto h-7 w-7 text-ag-green" /><p className="mt-2 text-sm font-bold text-white">All assigned work is complete</p></div>}</div></Card>
      <Card className="p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-wider text-ag-text-muted">Supplier arrival desk</p><h3 className="mt-1 text-lg font-bold text-white">Know who is actually here</h3><div className="mt-5 space-y-2">{suppliers.map((supplier) => <div key={supplier.id} className="flex items-center justify-between gap-3 rounded-xl border border-ag-border bg-ag-black/30 p-3"><div className="flex items-center gap-3"><div className={`rounded-lg p-2 ${supplier.status === 'on_site' ? 'bg-ag-green-dim text-ag-green' : 'bg-ag-surface text-ag-text-muted'}`}><MapPin className="h-4 w-4" /></div><div><p className="text-sm font-bold text-white">{supplier.name}</p><p className="mt-0.5 text-xs text-ag-text-secondary">{supplier.category}</p></div></div><button onClick={() => updateEventSupplier(supplier.id, { status: supplier.status === 'on_site' ? 'confirmed' : 'on_site' })} className={`rounded-md px-2.5 py-1.5 text-[11px] font-bold ${supplier.status === 'on_site' ? 'bg-ag-green-dim text-ag-green' : 'bg-ag-surface text-ag-text-secondary hover:text-white'}`}>{supplier.status === 'on_site' ? 'On site' : 'Check in'}</button></div>)}{suppliers.length === 0 && <p className="rounded-xl border border-dashed border-ag-border p-4 text-xs leading-relaxed text-ag-text-secondary">Suppliers added during readiness appear here for live arrival and handover tracking.</p>}</div></Card></div>
  </div>;
};

const DayMetric: React.FC<{ icon: React.ReactNode; label: string; value: string; detail: string; color: 'blue' | 'green' | 'yellow' }> = ({ icon, label, value, detail, color }) => <Card className="p-4"><div className={color === 'blue' ? 'text-ag-blue' : color === 'green' ? 'text-ag-green' : 'text-ag-yellow'}>{icon}</div><p className="mt-3 text-[11px] font-bold uppercase tracking-wider text-ag-text-muted">{label}</p><p className="mt-1 text-xl font-bold text-white">{value}</p><p className="mt-1 text-xs text-ag-text-secondary">{detail}</p></Card>;
