import React, { useMemo, useState } from 'react';
import { useAppStore } from '@/lib/store';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { formatCurrencyKES } from '@/lib/utils';
import { Banknote, CheckCircle2, Eye, Landmark, Plus, ReceiptText, ShieldCheck, Ticket, Users } from 'lucide-react';

type Lens = 'organiser' | 'finance' | 'supplier' | 'operations';

export const FinancialControl: React.FC<{ eventId: string; ticketRevenue: number }> = ({ eventId, ticketRevenue }) => {
  const { eventBudgetLines, eventPayments, createBudgetLine, createEventPayment, updateEventPayment } = useAppStore();
  const [lens, setLens] = useState<Lens>('organiser');
  const [showBudgetForm, setShowBudgetForm] = useState(false);
  const [showPaymentForm, setShowPaymentForm] = useState(false);
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('Production');
  const [amount, setAmount] = useState('');
  const [payee, setPayee] = useState('');
  const budgetLines = useMemo(() => eventBudgetLines.filter((line) => line.event_id === eventId), [eventBudgetLines, eventId]);
  const payments = useMemo(() => eventPayments.filter((payment) => payment.event_id === eventId), [eventPayments, eventId]);
  const planned = budgetLines.reduce((sum, line) => sum + line.planned_amount, 0);
  const committed = budgetLines.reduce((sum, line) => sum + line.committed_amount, 0);
  const paid = budgetLines.reduce((sum, line) => sum + line.paid_amount, 0) + payments.filter((payment) => payment.status === 'paid').reduce((sum, payment) => sum + payment.amount, 0);
  const paymentTotal = payments.reduce((sum, payment) => sum + payment.amount, 0);
  const addBudget = () => { const value = Number(amount); if (!description.trim() || !Number.isFinite(value) || value <= 0) return; createBudgetLine({ event_id: eventId, category, description: description.trim(), owner_name: 'Finance lead', planned_amount: value, committed_amount: 0, paid_amount: 0, status: 'draft' }); setDescription(''); setAmount(''); setShowBudgetForm(false); };
  const addPayment = () => { const value = Number(amount); if (!payee.trim() || !Number.isFinite(value) || value <= 0) return; createEventPayment({ event_id: eventId, supplier_id: null, payee_name: payee.trim(), description: description.trim() || 'Event supplier payment', amount: value, due_at: null, paid_at: null, status: 'awaiting_approval' }); setPayee(''); setDescription(''); setAmount(''); setShowPaymentForm(false); };
  const lenses: { id: Lens; label: string; description: string }[] = [{ id: 'organiser', label: 'Organiser', description: 'Full event health, commercial position and approvals.' }, { id: 'finance', label: 'Finance lead', description: 'Budget, payment approvals and reconciliation only.' }, { id: 'supplier', label: 'Supplier', description: 'Their brief, arrival window and payment status only.' }, { id: 'operations', label: 'Operations', description: 'Approved spend and delivery status—not supplier financial detail.' }];

  return <div className="space-y-5">
    <Card className="p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-ag-text-muted">Stakeholder workspace</p><h2 className="mt-1 text-xl font-bold text-white">One event truth. Different useful views.</h2></div><div className="flex flex-wrap gap-2">{lenses.map((item) => <button key={item.id} onClick={() => setLens(item.id)} className={`rounded-lg px-3 py-2 text-xs font-bold transition ${lens === item.id ? 'bg-ag-blue text-white' : 'bg-ag-black/40 text-ag-text-secondary hover:text-white'}`}>{item.label}</button>)}</div></div><div className="mt-4 flex items-start gap-2 rounded-xl border border-ag-border bg-ag-black/30 p-3 text-sm text-ag-text-secondary"><Eye className="mt-0.5 h-4 w-4 shrink-0 text-ag-blue" />{lenses.find((item) => item.id === lens)?.description}</div></Card>

    {lens === 'supplier' ? <SupplierView /> : lens === 'operations' ? <OperationsView /> : <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><FinanceMetric label="Ticket income" value={formatCurrencyKES(ticketRevenue)} icon={<Ticket className="h-4 w-4" />} tone="green" /><FinanceMetric label="Planned cost" value={formatCurrencyKES(planned)} icon={<ReceiptText className="h-4 w-4" />} tone="blue" /><FinanceMetric label="Committed" value={formatCurrencyKES(committed + paymentTotal)} icon={<Landmark className="h-4 w-4" />} tone="yellow" /><FinanceMetric label="Projected margin" value={formatCurrencyKES(ticketRevenue - Math.max(planned, committed + paymentTotal))} icon={<Banknote className="h-4 w-4" />} tone="purple" /></div>
      <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Card className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-ag-text-muted">Budget control</p><h3 className="mt-1 text-lg font-bold text-white">Plan before committing cash</h3></div><Button size="sm" variant="primary" onClick={() => setShowBudgetForm((open) => !open)} leftIcon={<Plus className="h-3.5 w-3.5" />}>Budget line</Button></div>{showBudgetForm && <div className="mt-4 grid gap-2 rounded-xl border border-ag-blue/40 bg-ag-blue-dim/20 p-3 sm:grid-cols-[1fr_1.2fr_.8fr_auto]"><input value={category} onChange={(event) => setCategory(event.target.value)} placeholder="Category" className="rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What is this for?" className="rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><input value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="numeric" placeholder="KES amount" className="rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><Button size="sm" variant="primary" onClick={addBudget}>Save</Button></div>}<div className="mt-5 space-y-2">{budgetLines.map((line) => <div key={line.id} className="flex items-center justify-between gap-3 rounded-xl border border-ag-border bg-ag-black/30 p-3"><div><p className="text-sm font-bold text-white">{line.description}</p><p className="mt-0.5 text-xs text-ag-text-secondary">{line.category} · {line.owner_name}</p></div><p className="font-mono text-sm font-bold text-ag-blue">{formatCurrencyKES(line.planned_amount)}</p></div>)}{budgetLines.length === 0 && <p className="rounded-xl border border-dashed border-ag-border p-4 text-xs leading-relaxed text-ag-text-secondary">Add the big commitments first: artist, venue, production, security, medical, marketing and logistics.</p>}</div></Card>
        <Card className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-ag-text-muted">Payment approval</p><h3 className="mt-1 text-lg font-bold text-white">Never lose a balance</h3></div><button onClick={() => setShowPaymentForm((open) => !open)} className="rounded-lg p-2 text-ag-blue hover:bg-ag-blue-dim" aria-label="Add payment"><Plus className="h-4 w-4" /></button></div>{showPaymentForm && <div className="mt-4 space-y-2 rounded-xl border border-ag-blue/40 bg-ag-blue-dim/20 p-3"><input value={payee} onChange={(event) => setPayee(event.target.value)} placeholder="Who is being paid?" className="w-full rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What is it for?" className="w-full rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><div className="flex gap-2"><input value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="numeric" placeholder="KES amount" className="min-w-0 flex-1 rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><Button size="sm" variant="primary" onClick={addPayment}>Request</Button></div></div>}<div className="mt-5 space-y-2">{payments.map((payment) => <div key={payment.id} className="rounded-xl border border-ag-border bg-ag-black/30 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-bold text-white">{payment.payee_name}</p><p className="mt-0.5 text-xs text-ag-text-secondary">{payment.description}</p></div><p className="font-mono text-sm font-bold text-ag-yellow">{formatCurrencyKES(payment.amount)}</p></div><button onClick={() => updateEventPayment(payment.id, { status: payment.status === 'paid' ? 'awaiting_approval' : 'paid', paid_at: payment.status === 'paid' ? null : new Date().toISOString() })} className="mt-3 flex items-center gap-1 text-[11px] font-bold text-ag-green"><CheckCircle2 className="h-3.5 w-3.5" />{payment.status === 'paid' ? 'Paid' : 'Mark paid'}</button></div>)}{payments.length === 0 && <p className="rounded-xl border border-dashed border-ag-border p-4 text-xs leading-relaxed text-ag-text-secondary">Every payment begins as a request, then becomes approved and paid—with a record the organiser can reconcile.</p>}</div></Card></div>
    </>}
  </div>;
};

const FinanceMetric: React.FC<{ label: string; value: string; icon: React.ReactNode; tone: 'green' | 'blue' | 'yellow' | 'purple' }> = ({ label, value, icon, tone }) => <Card className="p-4"><div className={`flex items-center gap-2 ${tone === 'green' ? 'text-ag-green' : tone === 'blue' ? 'text-ag-blue' : tone === 'yellow' ? 'text-ag-yellow' : 'text-ag-purple'}`}>{icon}<p className="text-[11px] font-bold uppercase tracking-wider text-ag-text-muted">{label}</p></div><p className="mt-3 text-lg font-bold text-white">{value}</p></Card>;
const SupplierView: React.FC = () => <Card className="p-6"><StoreFallback /><h3 className="mt-4 text-lg font-bold text-white">Supplier view: only what I need to deliver</h3><p className="mt-2 max-w-xl text-sm leading-relaxed text-ag-text-secondary">A supplier sees their scope, arrival window, contact person, documents, balance status and tasks. They never see the full event budget, other suppliers’ contracts, ticket revenue or security plan.</p></Card>;
const OperationsView: React.FC = () => <Card className="p-6"><div className="rounded-xl bg-ag-green-dim p-3 text-ag-green"><ShieldCheck className="h-5 w-5" /></div><h3 className="mt-4 text-lg font-bold text-white">Operations view: execution, not finance</h3><p className="mt-2 max-w-xl text-sm leading-relaxed text-ag-text-secondary">Gate, security and production teams see confirmed suppliers, arrival windows, run-sheet tasks and live operational signals. Commercial values remain with the organiser and finance lead.</p></Card>;
const StoreFallback: React.FC = () => <div className="rounded-xl bg-ag-blue-dim p-3 text-ag-blue"><Users className="h-5 w-5" /></div>;
