import React, { useMemo, useState } from 'react';
import { useAppStore } from '@/lib/store';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { CheckCircle2, CircleAlert, Clock3, Plus, Store, UserRoundCheck } from 'lucide-react';

const recommendedTasks = [
  ['Safety', 'Medical provider and evacuation plan confirmed', 'Safety lead'],
  ['Entry', 'Gate teams, scanners and holding lanes assigned', 'Gate manager'],
  ['Production', 'Stage, power and sound check complete', 'Production lead'],
  ['Talent', 'Artist arrival and backstage schedule confirmed', 'Artist liaison'],
  ['Comms', 'Guest arrival guide and gate map scheduled', 'Guest experience'],
] as const;

export const OperationsPlan: React.FC<{ eventId: string }> = ({ eventId }) => {
  const { eventTasks, eventSuppliers, createEventTask, updateEventTask, createEventSupplier, updateEventSupplier } = useAppStore();
  const [showTaskForm, setShowTaskForm] = useState(false);
  const [showSupplierForm, setShowSupplierForm] = useState(false);
  const [taskTitle, setTaskTitle] = useState('');
  const [taskOwner, setTaskOwner] = useState('');
  const [taskStream, setTaskStream] = useState('Operations');
  const [supplierName, setSupplierName] = useState('');
  const [supplierCategory, setSupplierCategory] = useState('');
  const tasks = useMemo(() => eventTasks.filter((task) => task.event_id === eventId), [eventTasks, eventId]);
  const suppliers = useMemo(() => eventSuppliers.filter((supplier) => supplier.event_id === eventId), [eventSuppliers, eventId]);
  const complete = tasks.filter((task) => task.status === 'complete').length;
  const blocked = tasks.filter((task) => task.status === 'blocked').length;
  const addTask = (title: string, owner: string, workstream: string) => { if (!title.trim()) return; createEventTask({ event_id: eventId, title: title.trim(), owner_name: owner.trim() || 'Unassigned', workstream, status: 'not_started', due_at: null, proof_url: null, notes: null }); setTaskTitle(''); setTaskOwner(''); setShowTaskForm(false); };
  const addSupplier = () => { if (!supplierName.trim()) return; createEventSupplier({ event_id: eventId, name: supplierName.trim(), category: supplierCategory.trim() || 'General supplier', contact_name: null, contact_phone: null, agreed_amount: null, deposit_paid: 0, balance_due: 0, status: 'shortlisted', arrival_window: null }); setSupplierName(''); setSupplierCategory(''); setShowSupplierForm(false); };

  return <div className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-3"><Card className="p-4"><p className="text-[11px] font-bold uppercase tracking-wider text-ag-text-muted">Operating tasks</p><p className="mt-2 text-2xl font-bold text-white">{tasks.length}</p><p className="mt-1 text-xs text-ag-text-secondary">{complete} confirmed complete</p></Card><Card className="p-4"><p className="text-[11px] font-bold uppercase tracking-wider text-ag-text-muted">Suppliers</p><p className="mt-2 text-2xl font-bold text-ag-blue">{suppliers.length}</p><p className="mt-1 text-xs text-ag-text-secondary">production, safety and guest experience</p></Card><Card className="p-4"><p className="text-[11px] font-bold uppercase tracking-wider text-ag-text-muted">Blocked work</p><p className={`mt-2 text-2xl font-bold ${blocked ? 'text-ag-red' : 'text-ag-green'}`}>{blocked}</p><p className="mt-1 text-xs text-ag-text-secondary">must be resolved before gates open</p></Card></div>
    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <Card className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-ag-text-muted">Operating plan</p><h2 className="mt-1 text-lg font-bold text-white">Every critical item has an owner</h2></div><Button size="sm" variant="primary" onClick={() => setShowTaskForm((open) => !open)} leftIcon={<Plus className="h-3.5 w-3.5" />}>Add task</Button></div>
        {showTaskForm && <div className="mt-5 grid gap-2 rounded-xl border border-ag-blue/40 bg-ag-blue-dim/20 p-3 sm:grid-cols-[1.4fr_1fr_1fr_auto]"><input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} placeholder="What must happen?" className="min-w-0 rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><input value={taskOwner} onChange={(event) => setTaskOwner(event.target.value)} placeholder="Owner" className="min-w-0 rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><input value={taskStream} onChange={(event) => setTaskStream(event.target.value)} placeholder="Workstream" className="min-w-0 rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><Button size="sm" variant="primary" onClick={() => addTask(taskTitle, taskOwner, taskStream)}>Save</Button></div>}
        <div className="mt-5 space-y-2">{tasks.map((task) => <div key={task.id} className="flex items-center gap-3 rounded-xl border border-ag-border bg-ag-black/30 p-3"><button onClick={() => updateEventTask(task.id, { status: task.status === 'complete' ? 'not_started' : 'complete' })} className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border ${task.status === 'complete' ? 'border-ag-green bg-ag-green-dim text-ag-green' : task.status === 'blocked' ? 'border-ag-red/50 bg-ag-red-dim text-ag-red' : 'border-ag-yellow/50 bg-ag-yellow-dim text-ag-yellow'}`}>{task.status === 'complete' ? <CheckCircle2 className="h-4 w-4" /> : task.status === 'blocked' ? <CircleAlert className="h-4 w-4" /> : <Clock3 className="h-4 w-4" />}</button><div className="min-w-0 flex-1"><p className="text-sm font-bold text-white">{task.title}</p><p className="mt-0.5 text-xs text-ag-text-secondary">{task.workstream} · {task.owner_name}</p></div><button onClick={() => updateEventTask(task.id, { status: task.status === 'blocked' ? 'in_progress' : 'blocked' })} className="text-[10px] font-bold uppercase tracking-wide text-ag-text-muted hover:text-ag-red">{task.status === 'blocked' ? 'Unblock' : 'Block'}</button></div>)}{tasks.length === 0 && <div className="rounded-xl border border-dashed border-ag-border p-4"><p className="text-sm font-semibold text-white">Start with the critical concert checklist</p><div className="mt-3 space-y-2">{recommendedTasks.map(([stream, title, owner]) => <button key={title} onClick={() => addTask(title, owner, stream)} className="flex w-full items-center justify-between rounded-lg bg-ag-surface px-3 py-2 text-left text-xs text-ag-text-secondary transition hover:bg-ag-surface-hover hover:text-white"><span>{title}</span><Plus className="h-3.5 w-3.5 text-ag-blue" /></button>)}</div></div>}</div>
      </Card>
      <Card className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-ag-text-muted">Supplier control</p><h2 className="mt-1 text-lg font-bold text-white">No more supplier guesswork</h2></div><button onClick={() => setShowSupplierForm((open) => !open)} className="rounded-lg p-2 text-ag-blue hover:bg-ag-blue-dim" aria-label="Add supplier"><Plus className="h-4 w-4" /></button></div>
        {showSupplierForm && <div className="mt-5 space-y-2 rounded-xl border border-ag-blue/40 bg-ag-blue-dim/20 p-3"><input value={supplierName} onChange={(event) => setSupplierName(event.target.value)} placeholder="Supplier name" className="w-full rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><input value={supplierCategory} onChange={(event) => setSupplierCategory(event.target.value)} placeholder="Category e.g. Sound & lighting" className="w-full rounded-lg border border-ag-border bg-ag-black px-3 py-2 text-sm text-white outline-none focus:border-ag-blue" /><Button size="sm" variant="primary" onClick={addSupplier}>Add supplier</Button></div>}
        <div className="mt-5 space-y-2">{suppliers.map((supplier) => <div key={supplier.id} className="rounded-xl border border-ag-border bg-ag-black/30 p-3"><div className="flex items-start gap-2"><Store className="mt-0.5 h-4 w-4 text-ag-blue" /><div className="min-w-0 flex-1"><p className="text-sm font-bold text-white">{supplier.name}</p><p className="mt-0.5 text-xs text-ag-text-secondary">{supplier.category}</p></div></div><button onClick={() => updateEventSupplier(supplier.id, { status: supplier.status === 'confirmed' ? 'contracted' : 'confirmed' })} className="mt-3 flex items-center gap-1 text-[11px] font-bold text-ag-green"><UserRoundCheck className="h-3.5 w-3.5" />{supplier.status === 'confirmed' ? 'Confirmed' : 'Mark confirmed'}</button></div>)}{suppliers.length === 0 && <p className="rounded-xl border border-dashed border-ag-border p-4 text-xs leading-relaxed text-ag-text-secondary">Track each provider—production, security, medics, catering, transport—with their confirmation and arrival status.</p>}</div>
      </Card>
    </div>
  </div>;
};
